name: "🚀 deploy to GH Pages"

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: 🚀 deploy to GH Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14.16.0
          registry-url: https://registry.npmjs.org
      - run: npm install
        # env:
        #   NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }} # You need to set this in your repo settings
      - run: npm run deploy
        # env:
        #   NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }} # You need to set this in your repo settings

